# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  ta9assignment:
    image: ta9assignment
    container_name: WebAPI
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8153:8153
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
